# Recordings to be used in tests
recordings:
  -
    id: spikeforest.paired_english.m15_190315_152315_cell1
    type: spikeforest
    parameters:
      study_name: paired_english
      recording_name: m15_190315_152315_cell1
    notes: A good example of a ground truth unit that has similar amplitude on two channels
  -
    id: spikeforest.paired_english.m113_191125_213423
    type: spikeforest
    parameters:
      study_name: paired_english
      recording_name: m113_191125_213423
    notes: ""
  -
    id: spikeforest.paired_kampff.2014_11_25_Pair_3_0
    type: spikeforest
    parameters:
      study_name: paired_kampff
      recording_name: 2014_11_25_Pair_3_0
    notes: ""

# Sorters to be used in tests
sorters:
  -
    id: mountainsort5
    type: spikeinterface
    algorithm: mountainsort5
    sorting_parameters: {}
  -
    id: spykingcircus2
    type: spikeinterface
    algorithm: spykingcircus2
    sorting_parameters: {}
  -
    id: kilosort2_5
    type: spikeinterface
    algorithm: kilosort2_5
    sorting_parameters: {}

# Combinations of recordings and sorters to be tested
sortings:
  -
    recording: spikeforest.paired_english.m15_190315_152315_cell1
    sorter: mountainsort5
  -
    recording: spikeforest.paired_english.m15_190315_152315_cell1
    sorter: kilosort2_5
  -
    recording: spikeforest.paired_english.m15_190315_152315_cell1
    sorter: spykingcircus2
  -
    recording: spikeforest.paired_english.m113_191125_213423
    sorter: mountainsort5
  -
    recording: spikeforest.paired_english.m113_191125_213423
    sorter: kilosort2_5
  -
    recording: spikeforest.paired_english.m113_191125_213423
    sorter: spykingcircus2
  -
    recording: spikeforest.paired_kampff.2014_11_25_Pair_3_0
    sorter: mountainsort5
  -
    recording: spikeforest.paired_kampff.2014_11_25_Pair_3_0
    sorter: kilosort2_5
  -
    recording: spikeforest.paired_kampff.2014_11_25_Pair_3_0
    sorter: spykingcircus2
  